Fix MPI compilation error by using include 'mpif.h' instead of use mpi
The 'use mpi' module statement doesn't work with all MPI implementations
(especially some mpifort configurations). Switching to the more universal
'include mpif.h' approach which is compatible with all OpenMPI versions.

Changes:
- mainSST.F90: Changed 'use mpi' to 'include mpif.h'
- data_loader_all.F90: Removed 'use mpi' from module and subroutines
- timeRoutines.F90: Changed 'use mpi' to 'include mpif.h'
- job_parameters.F90: Changed 'use mpi' to 'include mpif.h'

This fixes the error: 'mpi_barrier(mpi_comm_world,ierr) is not a variable'